# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userinterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg
try:
    import pyqtgraph.opengl as gl
    USE_GL = True
except ImportError:
    print("pyqtgraph.opengl not found")
    USE_GL = False


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 719)
        MainWindow.setStyleSheet("background-color: rgb(50, 50, 50);\n"
                                 "color: rgb(220, 220, 220);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setStyleSheet("QFrame {border-width: 3px;\n"
                                   "border-radius:10px;\n"
                                   "border-style: solid;\n"
                                   "border-color: rgb(150, 150, 150);\n"
                                   "}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(
            "QFrame {border-width: 0px;\nborder-radius:10px;\nborder-style: solid;\nborder-color: rgb(150, 150, 150);\\n}"
        )
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        # self.graphicsView_a0 = QtWidgets.QGraphicsView(self.frame_4)
        self.graphicsView_a0 = pg.PlotWidget(self.frame_4,
                                             background=(50, 50, 50),
                                             useOpenGL=USE_GL)
        self.graphicsView_a0.setObjectName("graphicsView_a0")
        self.verticalLayout_5.addWidget(self.graphicsView_a0)
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(
            "QFrame {border-width: 0px;\nborder-radius:10px;\nborder-style: solid;\nborder-color: rgb(150, 150, 150);\\n}"
        )
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        # self.graphicsView_a1 = QtWidgets.QGraphicsView(self.frame_4)
        self.graphicsView_a1 = pg.PlotWidget(self.frame_4,
                                             background=(50, 50, 50),
                                             useOpenGL=USE_GL)
        self.graphicsView_a1.setObjectName("graphicsView_a1")
        self.verticalLayout_5.addWidget(self.graphicsView_a1)
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(
            "QFrame {border-width: 0px;\nborder-radius:10px;\nborder-style: solid;\nborder-color: rgb(150, 150, 150);\\n}"
        )
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        # self.graphicsView_a2 = QtWidgets.QGraphicsView(self.frame_4)
        self.graphicsView_a2 = pg.PlotWidget(self.frame_4,
                                             background=(50, 50, 50),
                                             useOpenGL=USE_GL)
        self.graphicsView_a2.setObjectName("graphicsView_a2")
        self.verticalLayout_5.addWidget(self.graphicsView_a2)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setStyleSheet("QFrame {border-width: 3px;\n"
                                   "border-radius:10px;\n"
                                   "border-style: solid;\n"
                                   "border-color: rgb(150, 150, 150);\n"
                                   "}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.frame_6)
        self.label.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet(
            "QFrame {border-width: 0px;\nborder-radius:10px;\nborder-style: solid;\nborder-color: rgb(150, 150, 150);\\n}"
        )
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.checkBox_a0 = QtWidgets.QCheckBox(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.checkBox_a0.setFont(font)
        self.checkBox_a0.setStyleSheet("QCheckBox::indicator {\n"
                                       "    width: 30px;\n"
                                       "    height:30px;\n"
                                       "}")
        self.checkBox_a0.setChecked(True)
        self.checkBox_a0.setObjectName("checkBox_a0")
        self.verticalLayout_4.addWidget(self.checkBox_a0)
        self.checkBox_a1 = QtWidgets.QCheckBox(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.checkBox_a1.setFont(font)
        self.checkBox_a1.setStyleSheet("QCheckBox::indicator {\n"
                                       "    width: 30px;\n"
                                       "    height:30px;\n"
                                       "}")
        self.checkBox_a1.setChecked(True)
        self.checkBox_a1.setObjectName("checkBox_a1")
        self.verticalLayout_4.addWidget(self.checkBox_a1)
        self.checkBox_a2 = QtWidgets.QCheckBox(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.checkBox_a2.setFont(font)
        self.checkBox_a2.setStyleSheet("QCheckBox::indicator {\n"
                                       "    width: 30px;\n"
                                       "    height:30px;\n"
                                       "}")
        self.checkBox_a2.setChecked(True)
        self.checkBox_a2.setTristate(False)
        self.checkBox_a2.setObjectName("checkBox_a2")
        self.verticalLayout_4.addWidget(self.checkBox_a2)
        self.but_calibrate = QtWidgets.QPushButton(self.frame_6)
        self.but_calibrate.setMinimumSize(QtCore.QSize(0, 30))
        self.but_calibrate.setMaximumSize(QtCore.QSize(16777215, 40))
        self.but_calibrate.setStyleSheet(
            "QPushButton {\n"
            "   background-color: rgb(30, 30, 30);\n"
            "    color:  rgb(220, 220, 220);\n"
            "    border-style: outset;\n"
            "    padding: 1px;\n"
            "    font: bold 20px;\n"
            "    border-width: 2px;\n"
            "    border-radius: 10px;\n"
            "    border-color: rgb(220, 220, 220);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color:rgb(80, 80, 80);\n"
            "}")
        self.but_calibrate.setObjectName("but_calibrate")
        self.verticalLayout_4.addWidget(self.but_calibrate)
        self.but_calibrate_reset = QtWidgets.QPushButton(self.frame_6)
        self.but_calibrate_reset.setMinimumSize(QtCore.QSize(0, 30))
        self.but_calibrate_reset.setMaximumSize(QtCore.QSize(16777215, 40))
        self.but_calibrate_reset.setStyleSheet(
            "QPushButton {\n"
            "   background-color: rgb(30, 30, 30);\n"
            "    color:  rgb(220, 220, 220);\n"
            "    border-style: outset;\n"
            "    padding: 1px;\n"
            "    font: bold 20px;\n"
            "    border-width: 2px;\n"
            "    border-radius: 10px;\n"
            "    border-color: rgb(220, 220, 220);\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color:rgb(80, 80, 80);\n"
            "}")
        self.but_calibrate_reset.setObjectName("but_calibrate_reset")
        self.verticalLayout_4.addWidget(self.but_calibrate_reset)
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet(
            "QFrame {border-width: 0px;\nborder-radius:10px;\nborder-style: solid;\nborder-color: rgb(150, 150, 150);\\n}"
        )
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.lineEdit_maxbuffer = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_maxbuffer.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_maxbuffer.setFont(font)
        self.lineEdit_maxbuffer.setStyleSheet(
            "background-color: rgb(80, 80, 80);")
        self.lineEdit_maxbuffer.setObjectName("lineEdit_maxbuffer")
        self.verticalLayout_4.addWidget(self.lineEdit_maxbuffer)
        self.but_start = QtWidgets.QPushButton(self.frame_6)
        self.but_start.setMinimumSize(QtCore.QSize(0, 40))
        self.but_start.setMaximumSize(QtCore.QSize(16777215, 50))
        self.but_start.setStyleSheet("QPushButton {\n"
                                     "   background-color: rgb(30, 30, 30);\n"
                                     "    color:  rgb(220, 220, 220);\n"
                                     "    border-style: outset;\n"
                                     "    padding: 1px;\n"
                                     "    font: bold 20px;\n"
                                     "    border-width: 2px;\n"
                                     "    border-radius: 10px;\n"
                                     "    border-color: rgb(220, 220, 220);\n"
                                     "}\n"
                                     "QPushButton:hover {\n"
                                     "    background-color:rgb(80, 80, 80);\n"
                                     "}")
        self.but_start.setObjectName("but_start")
        self.verticalLayout_4.addWidget(self.but_start)
        self.but_stop = QtWidgets.QPushButton(self.frame_6)
        self.but_stop.setMinimumSize(QtCore.QSize(0, 40))
        self.but_stop.setMaximumSize(QtCore.QSize(16777215, 50))
        self.but_stop.setStyleSheet("QPushButton {\n"
                                    "   background-color: rgb(30, 30, 30);\n"
                                    "    color:  rgb(220, 220, 220);\n"
                                    "    border-style: outset;\n"
                                    "    padding: 1px;\n"
                                    "    font: bold 20px;\n"
                                    "    border-width: 2px;\n"
                                    "    border-radius: 10px;\n"
                                    "    border-color: rgb(220, 220, 220);\n"
                                    "}\n"
                                    "QPushButton:hover {\n"
                                    "    background-color:rgb(80, 80, 80);\n"
                                    "}")
        self.but_stop.setObjectName("but_stop")
        self.verticalLayout_4.addWidget(self.but_stop)
        self.but_saveas = QtWidgets.QPushButton(self.frame_6)
        self.but_saveas.setMinimumSize(QtCore.QSize(0, 40))
        self.but_saveas.setMaximumSize(QtCore.QSize(16777215, 50))
        self.but_saveas.setStyleSheet("QPushButton {\n"
                                      "   background-color: rgb(30, 30, 30);\n"
                                      "    color:  rgb(220, 220, 220);\n"
                                      "    border-style: outset;\n"
                                      "    padding: 1px;\n"
                                      "    font: bold 20px;\n"
                                      "    border-width: 2px;\n"
                                      "    border-radius: 10px;\n"
                                      "    border-color: rgb(220, 220, 220);\n"
                                      "}\n"
                                      "QPushButton:hover {\n"
                                      "    background-color:rgb(80, 80, 80);\n"
                                      "}")
        self.but_saveas.setObjectName("but_saveas")
        self.verticalLayout_4.addWidget(self.but_saveas)
        self.but_load = QtWidgets.QPushButton(self.frame_6)
        self.but_load.setMinimumSize(QtCore.QSize(150, 40))
        self.but_load.setMaximumSize(QtCore.QSize(16777215, 50))
        self.but_load.setStyleSheet("QPushButton {\n"
                                    "   background-color: rgb(30, 30, 30);\n"
                                    "    color:  rgb(220, 220, 220);\n"
                                    "    border-style: outset;\n"
                                    "    padding: 1px;\n"
                                    "    font: bold 20px;\n"
                                    "    border-width: 2px;\n"
                                    "    border-radius: 10px;\n"
                                    "    border-color: rgb(220, 220, 220);\n"
                                    "}\n"
                                    "QPushButton:hover {\n"
                                    "    background-color:rgb(80, 80, 80);\n"
                                    "}")
        self.but_load.setObjectName("but_load")
        self.verticalLayout_4.addWidget(self.but_load)
        self.but_reset = QtWidgets.QPushButton(self.frame_6)
        self.but_reset.setMinimumSize(QtCore.QSize(150, 40))
        self.but_reset.setMaximumSize(QtCore.QSize(16777215, 50))
        self.but_reset.setStyleSheet("QPushButton {\n"
                                     "   background-color: rgb(30, 30, 30);\n"
                                     "    color:  rgb(220, 220, 220);\n"
                                     "    border-style: outset;\n"
                                     "    padding: 1px;\n"
                                     "    font: bold 20px;\n"
                                     "    border-width: 2px;\n"
                                     "    border-radius: 10px;\n"
                                     "    border-color: rgb(220, 220, 220);\n"
                                     "}\n"
                                     "QPushButton:hover {\n"
                                     "    background-color:rgb(80, 80, 80);\n"
                                     "}")
        self.but_reset.setObjectName("but_reset")
        self.verticalLayout_4.addWidget(self.but_reset)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.horizontalLayout.addWidget(self.frame_5)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Channel A0"))
        self.label_3.setText(_translate("MainWindow", "Channel A1"))
        self.label_4.setText(_translate("MainWindow", "Channel A2"))
        self.label.setText(_translate("MainWindow", "Settings"))
        self.checkBox_a0.setText(_translate("MainWindow", "Channel A0"))
        self.checkBox_a1.setText(_translate("MainWindow", "Channel A1"))
        self.checkBox_a2.setText(_translate("MainWindow", "Channel A2"))
        self.but_calibrate.setText(_translate("MainWindow", "Calibrate"))
        self.but_calibrate_reset.setText(
            _translate("MainWindow", "Reset Calibration"))
        self.label_5.setText(_translate("MainWindow", "Max Buffer (s)"))
        self.but_start.setText(_translate("MainWindow", "Start"))
        self.but_stop.setText(_translate("MainWindow", "Stop"))
        self.but_saveas.setText(_translate("MainWindow", "Save As"))
        self.but_load.setText(_translate("MainWindow", "Load"))
        self.but_reset.setText(_translate("MainWindow", "Reset"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
